- name: "extract the zipped artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Install dependency NodeJS and NPM"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "start the app"
  command: pm2 start npm --start
